---
baseURL: https://mygotoblog.com
languageCode: en-us
title: My Go To Blog
pygmentsstyle: monokai
metaDataFormat: yaml
module:
  imports:
  - path: hugo-theme-novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
